spring.application.name=dpi-engine
server.port=8080

# Allow large PCAP file uploads (up to 500 MB)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Logging
logging.level.com.dpiengine=INFO

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration